title: "Records of The Pandora Archives"
description: "Records of everything written by 9"
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
